name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug info
        run: |
          echo "Host: ${{ secrets.HOST }}"
          echo "Password length: {{ secrets.PASSWORD }}"

      - name: Deploy to Alibaba Cloud
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/www/blog
            ls -la